---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
Dispalying the Moffett bank dataset 

```{r}
library("openxlsx")
library(caret)
library(tidyverse)
library(gmodels) # Cross Tables [CrossTable()]
library(ggmosaic) # Mosaic plot with ggplot [geom_mosaic()]
library(corrplot) # Correlation plot [corrplot()]
library(cowplot)
library(ggpubr)
library(MLmetrics)
library(summarytools)
library(ROCR) # Model performance [performance(), prediction()]
library(plotROC) # ROC Curve with ggplot [geom_roc()]
library(pROC) #


bank_data <- read.xlsx("C:\\Users\\Amulya\\Desktop\\Aryng\\Excerise_solutions_PA\\Moffett_Bank.xlsx",1)
bank_data
dim(bank_data)
str(bank_data)
view(dfSummary(bank_data))
names(bank_data)
CrossTable(bank_data$y)
bank_data = bank_data %>% 
  mutate(y = factor(if_else(y == "yes", "1", "0"), 
                    levels = c("0", "1")))
sum(is.na(bank_data))
sum(bank_data == "unknown")
bank_data %>% 
  summarise_all(list(~sum(. == "unknown"))) %>% 
  gather(key = "variable", value = "nr_unknown") %>% 
  arrange(-nr_unknown)



```

```{r}

########################################################################################
fun_crosstable = function(df, var1, var2){
  # df: dataframe containing both columns to cross
  # var1, var2: columns to cross together.
  CrossTable(df[, var1], df[, var2],
             prop.r = T,
             prop.c = F,
             prop.t = F,
             prop.chisq = F,
             dnn = c(var1, var2))
}



# re-ordering levels from factor variable
fun_reorder_levels = function(df, variable, first){
  # df: dataframe containing columns to transform into factors
  # variable: variable to transform into factor
  # first: first level of the variable to transform.
  
  remaining = unique(df[, variable])[which(unique(df[, variable]) != first)]
  x = factor(df[, variable], levels = c(first, remaining))
  return(x)
}


# plotting importance from predictive models into two panels
fun_imp_ggplot_split = function(model){
  # model: model used to plot variable importances
  
  if (class(model)[1] == "ranger"){
    imp_df = model$variable.importance %>% 
      data.frame("Overall" = .) %>% 
      rownames_to_column() %>% 
      rename(variable = rowname) %>% 
      arrange(-Overall)
  } else {
    imp_df = varImp(model) %>%
      rownames_to_column() %>% 
      rename(variable = rowname) %>% 
      arrange(-Overall)
  }
  
  # first panel (half most important variables)
  gg1 = imp_df %>% 
    slice(1:floor(nrow(.)/2)) %>% 
    ggplot() +
    aes(x = reorder(variable, Overall), weight = Overall, fill = -Overall) +
    geom_bar() +
    coord_flip() +
    xlab("Variables") +
    ylab("Importance") +
    theme(legend.position = "none")
  
  imp_range = ggplot_build(gg1)[["layout"]][["panel_params"]][[1]][["x.range"]]
  imp_gradient = scale_fill_gradient(limits = c(-imp_range[2], -imp_range[1]),
                                     low = "#132B43", 
                                     high = "#56B1F7")
  
  # second panel (less important variables)
  gg2 = imp_df %>% 
    slice(floor(nrow(.)/2)+1:nrow(.)) %>% 
    ggplot() +
    aes(x = reorder(variable, Overall), weight = Overall, fill = -Overall) +
    geom_bar() +
    coord_flip() +
    xlab("") +
    ylab("Importance") +
    theme(legend.position = "none") +
    ylim(imp_range) +
    imp_gradient
  
  # arranging together
  gg_both = plot_grid(gg1 + imp_gradient,
                      gg2)
  
  return(gg_both)
}

# plotting two performance measures
fun_gg_cutoff = function(score, obs, measure1, measure2) {
  # score: predicted scores
  # obs: real classes
  # measure1, measure2: which performance metrics to plot
  
  predictions = prediction(score, obs)
  performance1 = performance(predictions, measure1)
  performance2 = performance(predictions, measure2)
  
  df1 = data.frame(x = performance1@x.values[[1]],
                   y = performance1@y.values[[1]],
                   measure = measure1,
                   stringsAsFactors = F) %>% 
    drop_na()
  df2 = data.frame(x = performance2@x.values[[1]],
                   y = performance2@y.values[[1]],
                   measure = measure2,
                   stringsAsFactors = F) %>% 
    drop_na()
  
  # df contains all the data needed to plot both curves
  df = df1 %>% 
    bind_rows(df2)
  
  # extracting best cut for each measure
  y_max_measure1 = max(df1$y, na.rm = T)
  x_max_measure1 = df1[df1$y == y_max_measure1, "x"][1]
  
  y_max_measure2 = max(df2$y, na.rm = T)
  x_max_measure2 = df2[df2$y == y_max_measure2, "x"][1]
  
  txt_measure1 = paste("Best cut for", measure1, ": x =", round(x_max_measure1, 3))
  txt_measure2 = paste("Best cut for", measure2, ": x =", round(x_max_measure2, 3))
  txt_tot = paste(txt_measure1, "\n", txt_measure2, sep = "")
  
  # plotting both measures in the same plot, with some detail around.
  gg = df %>% 
    ggplot() +
    aes(x = x,
        y = y,
        colour = measure) +
    geom_line() +
    geom_vline(xintercept = c(x_max_measure1, x_max_measure2), linetype = "dashed", color = "gray") +
    geom_hline(yintercept = c(y_max_measure1, y_max_measure2), linetype = "dashed", color = "gray") +
    labs(caption = txt_tot) +
    theme(plot.caption = element_text(hjust = 0)) +
    xlim(c(0, 1)) +
    ylab("") +
    xlab("Threshold")
  
  return(gg)
}

# creating classes according to score and cut
fun_cut_predict = function(score, cut) {
  # score: predicted scores
  # cut: threshold for classification
  
  classes = score
  classes[classes > cut] = 1
  classes[classes <= cut] = 0
  classes = as.factor(classes)
  
  return(classes)  
}







```
```{r}


########################################################################################

summary(bank_data$age)
bank_data %>% 
  ggplot() +
  aes(x = age) +
  geom_bar() +
  geom_vline(xintercept = c(30, 60), 
             col = "red",
             linetype = "dashed") +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 100, 5))


bank_data = bank_data %>% 
  mutate(age = if_else(age > 60, "high", if_else(age > 30, "mid", "low")))
fun_crosstable(bank_data, "age", "y")


table(bank_data$job)
fun_crosstable(bank_data, "job", "y")
bank_data = bank_data %>% 
  filter(job != "unknown")
ggplot(bank_data,aes(job,fill=y))+geom_bar()+
  ggtitle("Job vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )
chisq.test(bank_data$job, bank_data$y)

fun_crosstable(bank_data, "marital", "y")
bank_data = bank_data %>% 
  filter(marital != "unknown")
ggplot(bank_data,aes(marital,fill=y))+geom_bar()+
  ggtitle("Marital vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )
chisq.test(bank_data$marital, bank_data$y)

fun_crosstable(bank_data, "education", "y")
bank_data = bank_data %>% 
  filter(education != "illiterate")
chisq.test(bank_data$education, bank_data$y)
ggplot(bank_data,aes(education,fill=y))+geom_bar()+
  ggtitle("Education vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )

fun_crosstable(bank_data, "default", "y")
bank_data = bank_data %>% 
  select(-default)

fun_crosstable(bank_data, "housing", "y")
chisq.test(bank_data$housing, bank_data$y)
bank_data = bank_data %>% 
  select(-housing)

fun_crosstable(bank_data, "loan", "y")
chisq.test(bank_data$loan, bank_data$y)
bank_data = bank_data %>% 
  select(-loan)

fun_crosstable(bank_data, "contact", "y")
chisq.test(bank_data$contact, bank_data$y)
ggplot(bank_data,aes(contact,fill=y))+geom_bar()+
  ggtitle("Contact vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )


fun_crosstable(bank_data, "month", "y")
chisq.test(bank_data$month, bank_data$y)
ggplot(bank_data,aes(month,fill=y))+geom_bar()+
  ggtitle("Month vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )


fun_crosstable(bank_data, "day_of_week", "y")
chisq.test(bank_data$day_of_week, bank_data$y)
ggplot(bank_data,aes(day_of_week,fill=y))+geom_bar()+
  ggtitle("Day of week vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )

bank_data = bank_data %>% 
  select(-duration)

bank_data %>% 
  ggplot() +
  aes(x = campaign) +
  geom_bar() +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 50, 5))
bank_data = bank_data %>% 
  filter(campaign <= 10)
bank_data %>% 
  ggplot() +
  aes(x = campaign) +
  geom_bar() +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 10, 1))
fun_crosstable(bank_data, "campaign", "y")
ggplot(bank_data,aes(campaign,fill=y))+geom_bar()+
  ggtitle("Campaign vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )
bank_data = bank_data %>% 
  mutate(campaign = as.character(campaign))


bank_data = bank_data %>% 
  mutate(pdays_dummy = if_else(pdays == 999, "0", "1")) %>% 
  select(-pdays)
fun_crosstable(bank_data, "pdays_dummy", "y")


table(bank_data$previous)
bank_data = bank_data %>% 
  mutate(previous = if_else(previous >=  2, "2+", if_else(previous == 1, "1", "0")))
fun_crosstable(bank_data, "previous", "y")
ggplot(bank_data,aes(previous,fill=y))+geom_bar()+
  ggtitle("Previous vs term deposit")+
  theme(axis.text.x = element_text(angle =90,vjust = 0.5) )

fun_crosstable(bank_data, "poutcome", "y")


bank_data %>% 
  select(emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed) %>% 
  cor() %>% 
  corrplot(method = "number",
           type = "upper",
           tl.cex = 0.8,
           tl.srt = 45,
           tl.col = "black")
bank_data = bank_data %>% 
  select(-emp.var.rate)

#bank_data = bank_data %>% 
  #select(-euribor3m)

#bank_data = bank_data %>% 
  #select(-nr.employed)



bank_data
########################################################################################

bank_data$age = fun_reorder_levels(bank_data, "age", "low")
bank_data$job = fun_reorder_levels(bank_data, "job", "unemployed")
bank_data$marital = fun_reorder_levels(bank_data, "marital", "single")
bank_data$education = fun_reorder_levels(bank_data, "education", "basic.4y")
bank_data$contact = fun_reorder_levels(bank_data, "contact", "telephone")
bank_data$month = fun_reorder_levels(bank_data, "month", "mar")
bank_data$day_of_week = fun_reorder_levels(bank_data, "day_of_week", "mon")
bank_data$campaign = fun_reorder_levels(bank_data, "campaign", "1")
bank_data$previous = fun_reorder_levels(bank_data, "previous", "0")
bank_data$poutcome = fun_reorder_levels(bank_data, "poutcome", "nonexistent")
bank_data$pdays_dummy = fun_reorder_levels(bank_data, "pdays_dummy", "0")

#bank_data

####################################################################(model)
set.seed(1234)

ind = createDataPartition(bank_data$y,
                          times = 1,
                          p = 0.8,
                          list = F)
bank_train = bank_data[ind, ]
bank_test = bank_data[-ind, ]

logistic = glm(y ~ .,
               data = bank_train,
               family = "binomial")

summary(logistic)


fun_imp_ggplot_split(logistic)
imp=(varImp(logistic))
imp

logistic_train_score = predict(logistic,newdata = bank_train,type = "response")
logistic_test_score = predict(logistic,newdata = bank_test,type = "response")


measure_train = fun_gg_cutoff(logistic_train_score, bank_train$y, "acc", "f")
measure_train +
  geom_vline(xintercept = c(0.2, 0.5), 
             linetype = "dashed")

logistic_train_cut = 0.2
logistic_train_class = fun_cut_predict(logistic_train_score, logistic_train_cut)

# matrix
logistic_train_confm = confusionMatrix(logistic_train_class, bank_train$y, 
                                       positive = "1",
                                       mode = "everything")
logistic_train_confm



#validation
measure_test = fun_gg_cutoff(logistic_test_score, bank_test$y,"acc", "f")
measure_test +
  geom_vline(xintercept = c(logistic_train_cut, 0.5), linetype = "dashed")

logistic_test_class = fun_cut_predict(logistic_test_score, logistic_train_cut)

# matrix
logistic_test_confm = confusionMatrix(logistic_test_class, bank_test$y, 
                                      positive = "1",
                                      mode = "everything")
logistic_test_confm




#############################################################################


``````
